sudo: false
language: java

jdk:
- oraclejdk8
# - openjdk10

# cache local Maven repo: https://docs.travis-ci.com/user/caching/
cache:
  directories:
  - $HOME/.m2/repository

before_cache:
  - rm -rf $HOME/.m2/repository/net/oneandone/ioc-unit/

env:
- PROFILES=base,weld3.0,junit4
- PROFILES=base,weld2.3,junit4
- PROFILES=base,weld1.1,junit4
- PROFILES=arquillian
- PROFILES=base,weld2.3,junit5

script: "mvn clean install -P${PROFILES}"

