sudo: false
language: java

jdk:
- openjdk8
# - openjdk11

# cache local Maven repo: https://docs.travis-ci.com/user/caching/
cache:
  directories:
  - $HOME/.m2/repository

before_cache:
  - rm -rf $HOME/.m2/repository/net/oneandone/ioc-unit/

env:
- PROFILES=base,weld3.1,junit4,bomjavaee80
- PROFILES=base,weld2.3,junit4,bomwf10
- PROFILES=base,weld1.1,junit4
- PROFILES=arquillian
- PROFILES=base,weld2.3,junit5,bomjavaee70

script: "mvn -B clean install -P${PROFILES}"

